// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDoHs_7O-lZ2PCXW30XBrNkw2IICCsay4',
    appId: '1:631128095988:web:d61e719234a144cd51b2a1',
    messagingSenderId: '631128095988',
    projectId: 'ozod-loyalty',
    authDomain: 'ozod-loyalty.firebaseapp.com',
    storageBucket: 'ozod-loyalty.appspot.com',
    measurementId: 'G-DJ5TYKXY54',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDH3Co4yjNeQgeohB4vIU4fEcq0TMvSCjs',
    appId: '1:631128095988:android:8196f18eab8bdd5551b2a1',
    messagingSenderId: '631128095988',
    projectId: 'ozod-loyalty',
    storageBucket: 'ozod-loyalty.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVjW4FzBVSvu1PRgcT_21QhEe3dy354eM',
    appId: '1:631128095988:ios:61ba2b2aad3e2bb051b2a1',
    messagingSenderId: '631128095988',
    projectId: 'ozod-loyalty',
    storageBucket: 'ozod-loyalty.appspot.com',
    androidClientId: '631128095988-aucjv7trij1lh6emvialdkqteg8n6igv.apps.googleusercontent.com',
    iosClientId: '631128095988-pc4m1sersb2su65cjs5jgsmvo9mnhtdt.apps.googleusercontent.com',
    iosBundleId: 'com.ozod.wallet.ozodwallet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVjW4FzBVSvu1PRgcT_21QhEe3dy354eM',
    appId: '1:631128095988:ios:61ba2b2aad3e2bb051b2a1',
    messagingSenderId: '631128095988',
    projectId: 'ozod-loyalty',
    storageBucket: 'ozod-loyalty.appspot.com',
    androidClientId: '631128095988-aucjv7trij1lh6emvialdkqteg8n6igv.apps.googleusercontent.com',
    iosClientId: '631128095988-pc4m1sersb2su65cjs5jgsmvo9mnhtdt.apps.googleusercontent.com',
    iosBundleId: 'com.ozod.wallet.ozodwallet',
  );
}
